### ISSUE TITLE
Unpublished Yarn Berry files

### ISSUE THREAD

**Issue by quinnturner** [launchdarkly/jest-launchdarkly-mock#27]
**Describe the bug**
When using Yarn Zero Installs, you are not intended to publish the dependencies (any of the Yarn files) to the registry.

Accordingly, this package is WAY too large on the NPM registry.

**Comment by yusinto** [comment]
Thanks for reporting this. This is now fixed in [v1.0.2](https://github.com/launchdarkly/jest-launchdarkly-mock/releases/tag/1.0.2).
