### ISSUE TITLE
WithLDConsumer returns null

### ISSUE THREAD

**Issue by debaraj-barua** [launchdarkly/jest-launchdarkly-mock#28]
From my perspective, `WithLDConsumer` should not return `null` while mocking, it should return the children instead.

https://github.com/launchdarkly/jest-launchdarkly-mock/blob/d3e792082b4e3743cff63c331e92341a82ed1574/src/index.ts#L55

This leads to errors like
![image](https://user-images.githubusercontent.com/15277963/169880158-34cb8512-351a-424c-9f0d-d3c2095d7a69.png)
when mocking

**Comment by carmenquan** [comment]
@debaraj-barua thanks for opening the PR - our team will look at it soon.
