### ISSUE TITLE
useLDClientError is missing from the mocks

### ISSUE THREAD

**Issue by manelmadeira** [launchdarkly/jest-launchdarkly-mock#47]
**Describe the bug**

When testing code with `jest` that contains the hook `useLDClientError` from `launchdarkly-react-client-sdk` we get the following error:

`Error: Uncaught [TypeError: (0 , _launchdarklyReactClientSdk.useLDClientError) is not a function]`

**Comment by yusinto** [comment]
This has been added in [2.0.1](https://github.com/launchdarkly/jest-launchdarkly-mock/releases/tag/2.0.1).
